### ISSUE TITLE
eof.compute_coefficient still uses the structure of old IO

### ISSUE THREAD

**Issue by Luantimes2** [michael-petersen/exptool#15]
eof.compute_coefficient code still uses PSPInput as the old file stream. For example, PSPInput.xpos, which should be replace by PSPInput.x now

**Comment by michael-petersen** [comment]
Okay, I see what you mean. The fastest fix is to tick 'legacy=True' when opening a PSP file. I checked in a minimal fix for eof.compute_coefficients, but I will design a cleaner overhaul as well.

**Comment by Luantimes2** [comment]
legacy=True should fix that, but in current version, psp_io and spl_io do not support legacy parameter.

**Comment by michael-petersen** [comment]
That's right, legacy=True compatibility was moved up to particle.py (if you're working within exptool, you shouldn't need to call psp_io or spl_io directly, particle.Input() will call out to the correct file format by default). So you can do something like 
`from exptool.io import particle`
`PSPInput = particle.Input(filename, component, legacy=True)`
and then feed in to the relevant eof.py code.

**Comment by michael-petersen** [comment]
I'm closing this for now, but if the functionality is a pain, we'll change it.
