### ISSUE TITLE
Assumed .infile - comment out or write toggle?

### ISSUE THREAD

**Issue by CarrieFilion** [michael-petersen/exptool#19]
Is it ok if I comment out the following lines?
`SL_Out.dump = PSPInput.infile` in /basis/spheresl.py
`EOF_Out.dump = PSPInput.infile` in /basis/eof.py
What purpose do they serve?

Reasoning below -
If you transform into the bar frame, you can run get_fields just fine without adjustments to the eof or spheresl files. However, if you do NOT transform into the barframe, you get an error that PSPInput does not have a .infile attribute. I could build in a toggle to recognize if the PSPInput file is a BarTransform object or just a regular PSP file if, for some reason, just commenting out those two lines is a no-go

**Comment by michael-petersen** [comment]
The short answer to your question is that you can comment those out, but I suspect you would also have to comment out line 144 in `analysis/pattern.py`. 

In theory those lines were meant to make sure that you could keep track of which file was input for the analysis (just a safeguard in case one forgets what file was used to construct the potential). However, at some point I (half) deprecated `.infile` in favour of `.filename` and forgot to update everywhere. I just pushed a fix(?) to convert everything in `basis/potential.py` to be `.filename`. The error was probably coming from `analysis/pattern.py`, which also had the old-style `.infile` in it. I also modified that. It is possible that you will have to regenerate the `Fields()` instance now, but I think the binary format doesn't care about `.dump` (also deprecated now, old holdover from EXP itself), `.infile`, and `.filename`.

**Comment by michael-petersen** [comment]
I'm closing this for now, but this can be reopened if the bug persists, or has a new form.
